# Copyright (c) 2016-2018 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Rubeus Developers
site_description: Página de documentações da Rubeus
site_author: Rubeus
site_url: https://docs.rubeus.com.br/

# Repository
# repo_name: RubeusTI/docs
# repo_url: https://github.com/RubeusTI/docs
# edit_uri: ""

# Copyright
copyright: '&copy; 2020 Rubeus todos os direitos reservados'

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: pt
  feature:
    tabs: true
  palette:
    primary: Teal
    accent: Teal
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo: "assets/images/logo.svg"

# Customization

extra_css:
  - 'assets/stylesheets/extra.css'

extra_javascript:
  - 'assets/javascripts/extra.js'

extra:
  search:
    language: 'pt'
  social:
    - type: globe
      link: https://rubeus.com.br/
    - type: instagram
      link: https://www.instagram.com/canalrubeus/
    - type: facebook
      link: https://www.facebook.com/CanalRubeus/
    - type: linkedin
      link: https://www.linkedin.com/company/rubeus/
    - type: twitter
      link: https://twitter.com/CanalRubeus
    - type: github
      link: https://github.com/RubeusTI

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: true
      linenums: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  # - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      # legacy_tab_classes: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - API CRM:
    - Apresentação: api_crm/apresentacao.md
    - Contato: api_crm/contato.md
    - Evento: api_crm/evento.md
    - Campos personalizados: api_crm/campopersonalizados.md
    - Processo seletivo: api_crm/processoseletivo.md
    - Curso: api_crm/curso.md
    - Locais de oferta: api_crm/locaisdeoferta.md
    - Registro de processo: api_crm/registrodeprocesso.md
    - Unidade: api_crm/unidade.md
    - Métodos de listagem: api_crm/metodosdelistagem.md
    # - Usuários: api_crm/usuarios.md
  - Webhook: webhook.md
  - Endpoint: endpoint.md
  - Monitoramento de páginas:
    - Apresentação: monitoramento/apresentacao.md
    - Instalação: monitoramento/instalacao.md
    - Enviando eventos: monitoramento/enviando-eventos.md
    - Enviando dados de contato: monitoramento/enviando-data.md
    - Boas práticas: monitoramento/boas-praticas.md
    - Exemplos de códigos: monitoramento/exemplos-codigos.md
    - Integração via API: monitoramento/integracao-api.md
    - Utilizando o modo manual: monitoramento/modo-manual.md
    # - Recuperando informações: monitoramento/recuperando-informacoes.md
    # - Tracking multidomínio: monitoramento/tracking-multidominio.md
  - Tabelas auxiliares: tabelasauxiliares.md
  - Gerador de URL's: urlbuilder.md
  # - Testar API's: methodstest.md


# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto